### ISSUE TITLE
Metadata attributes (owner, group, permissions) are not all lower case

### ISSUE THREAD

**Issue by simonlindblad** [wastore/lemur#13]
These attributes should be stored as lower case to be compatible with: https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update

It's also incompatible with https://github.com/microsoft/amlFilesystem-hydrator which only expects lower case metadata fields.

**Comment by zezha-msft** [comment]
Relevant code here: https://github.com/wastore/lemur/blob/master/cmd/lhsm-plugin-az-core/archive.go#L78

**Comment by zezha-msft** [comment]
Mitigated.
