### ISSUE TITLE
Archiving should store the permissions in octal format (4-digit) or symbolic

### ISSUE THREAD

**Issue by simonlindblad** [wastore/lemur#14]
This is to stay coherent with: https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update

"Optional and only valid if Hierarchical Namespace is enabled for the account. Sets POSIX access permissions for the file owner, the file owning group, and others. Each class may be granted read, write, or execute permission. The sticky bit is also supported. Both symbolic (rwxrw-rw-) and 4-digit octal notation (e.g. 0766) are supported. Invalid in conjunction with x-ms-acl."

And the hydrator: https://github.com/microsoft/amlFilesystem-hydrator

**Comment by simonlindblad** [comment]
I think it can be solved by changing:
`permissions := fmt.Sprintf("%o", fileInfo.Mode())`
to `permissions := fmt.Sprintf("%#o", fileInfo.Mode())`

in https://github.com/wastore/lemur/blob/master/cmd/lhsm-plugin-az-core/archive.go

**Comment by zezha-msft** [comment]
Fixed.
