### ISSUE TITLE
Failing to archive large file (100 GB+)

### ISSUE THREAD

**Issue by simonlindblad** [wastore/lemur#23]
Failure seen in syslog:
`2021/05/27 16:41:00 Archiving <redacted_for_issue>. Failed to upload blob: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /usr/src/lemur_wastore/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201027154117-4e8f2d48550b/azblob/zc_storage_error.go:42#012===== RESPONSE ERROR (ServiceCode=RequestBodyTooLarge) =====#012Description=The request body is too large and exceeds the maximum permissible limit.#012RequestId:2cfaf48a-101e-0003-4217-53f150000000#012Time:2021-05-27T16:41:00.4027471Z, Details: #012 Code: RequestBodyTooLarge#012 MaxLimit: 4194304000#012 PUT <redacted_for_issue> &timeout=901#012 Content-Length: [549757180040]#012 User-Agent: [Azure-Storage/0.10 (go1.14; linux)]#012 X-Ms-Client-Request-Id: [676f55b5-56a4-43f8-5860-c6e4dff0e2ed]#012 X-Ms-Version: [2019-12-12]#012 --------------------------------------------------------------------------------#012 RESPONSE Status: 413 The request body is too large and exceeds the maximum permissible limit.#012 Content-Length: [291]#012 Content-Type: [application/xml]#012 Date: [Thu, 27 May 2021 16:41:00 GMT]#012 Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012 X-Ms-Client-Request-Id: [676f55b5-56a4-43f8-5860-c6e4dff0e2ed]#012 X-Ms-Error-Code: [RequestBodyTooLarge]#012 X-Ms-Request-Id: [2cfaf48a-101e-0003-4217-53f150000000]#012 X-Ms-Version: [2019-12-12]#012#012#012`

**Comment by nakulkar-msft** [comment]
Fixed in dev
